-- ATLAS schema v1 — bars + signals + outcomes.
-- Idempotent: safe to re-run, but the migrate runner only runs each file once.

CREATE TABLE IF NOT EXISTS bars (
    ts          TIMESTAMPTZ NOT NULL,
    symbol      TEXT        NOT NULL,
    resolution  TEXT        NOT NULL,
    open        DOUBLE PRECISION,
    high        DOUBLE PRECISION,
    low         DOUBLE PRECISION,
    close       DOUBLE PRECISION,
    volume      DOUBLE PRECISION,
    vwap        DOUBLE PRECISION,
    trade_count INTEGER,
    PRIMARY KEY (symbol, resolution, ts)
);

-- TimescaleDB hypertable (idempotent via if_not_exists).
SELECT create_hypertable(
    'bars', 'ts',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS bars_symbol_ts_idx ON bars (symbol, ts DESC);

-- Signals — generated by scoring-engine, served by signal-service.
CREATE TABLE IF NOT EXISTS signals (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol             TEXT NOT NULL,
    asset_class        TEXT NOT NULL,
    generated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    horizon            TEXT NOT NULL,
    direction          TEXT NOT NULL,
    composite_score    NUMERIC(6,2) NOT NULL,
    confidence_pct     NUMERIC(5,2) NOT NULL,
    conviction         TEXT NOT NULL,
    regime             TEXT NOT NULL,
    entry_price        NUMERIC(20,8),
    stop_price         NUMERIC(20,8),
    take_profit_levels NUMERIC(20,8)[],
    position_size_pct  NUMERIC(6,3),
    expected_rr        NUMERIC(6,2),
    rationale_md       TEXT,
    sub_scores         JSONB NOT NULL DEFAULT '{}'::jsonb,
    model_versions     JSONB NOT NULL DEFAULT '{}'::jsonb,
    status             TEXT NOT NULL DEFAULT 'open'
);

CREATE INDEX IF NOT EXISTS signals_symbol_time_idx ON signals (symbol, generated_at DESC);
CREATE INDEX IF NOT EXISTS signals_status_idx ON signals (status) WHERE status = 'open';

CREATE TABLE IF NOT EXISTS signal_outcomes (
    signal_id        UUID PRIMARY KEY REFERENCES signals(id) ON DELETE CASCADE,
    exit_price       NUMERIC(20,8),
    exit_time        TIMESTAMPTZ,
    exit_reason      TEXT,
    realized_return  NUMERIC(10,6),
    max_drawdown     NUMERIC(10,6),
    max_run_up       NUMERIC(10,6),
    hit              BOOLEAN
);
